### ISSUE TITLE
Classes Count, TimestampRange not exported in index.d.ts, Missing options

### ISSUE THREAD

**Issue by emmanuelnk** [averias/redis-time-series#20]
Thanks for making this library, its been very helpful! However there are some big issues.

`TimestampRange` and `Count` are not exported correctly. They are missing in the below export:

https://github.com/averias/redis-time-series/blob/fdc522eaf7e137f23c0a2c9e968184802b18043d/src/index.ts#L22

I've made a PR I will reference soon that tries to fix many of the issues (update to the latest spec with TS.MREVRANGE, TS.REVRANGE, `CHUNK_SIZE, DUPLICATE_POLICY` on `TS.CREATE/TS.ALTER`, `ON_DUPLICATE` on `TS.ADD`). I've tried to follow the spec as much as possible so I may have missed some things. Hope you can look it over and provide input. Thanks.

**Comment by emmanuelnk** [comment]
Until maintainer merges PR, future users can use my [fork](https://www.npmjs.com/package/@emmanuelnk/redis-time-series-ts):
```
npm install @emmanuelnk/redis-time-series-ts
```

**Comment by averias** [comment]
Hi @emmanuelnk thank you so much for taking care of updating and solving issues in this project. Sorry, I've not had time enough for maintaining it lately for personal reasons but I think that I can take care of it again from now. I've taken a look at your PR and looks ok, so I'll merge it to master and publish it in the next days

**Comment by emmanuelnk** [comment]
@averias Thanks for getting back! I thought you had abandoned the project. Glad to see you can still amintain it. I've added even more updates. I've updated the docs to reflect the proper way to import classes and I've also added missing option `UNCOMPRESSED` on some of the commands. I've also added tsdoc documentation on the public exported classes and functions. I'll make a PR tomorrow with these changes.

Thanks. And again, great work on the library

**Comment by averias** [comment]
@emmanuelnk amazing!! ok, in that case, I'll wait for your PR and then I will publish new minor version. Thank you so much again and amazing job!
